package comuxi.example.administrator.panda_channel.MyCollectGreeDao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import comuxi.example.administrator.panda_channel.MyCollectGreeDao.CollectionGreeDao;

import comuxi.example.administrator.panda_channel.MyCollectGreeDao.CollectionGreeDaoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig collectionGreeDaoDaoConfig;

    private final CollectionGreeDaoDao collectionGreeDaoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        collectionGreeDaoDaoConfig = daoConfigMap.get(CollectionGreeDaoDao.class).clone();
        collectionGreeDaoDaoConfig.initIdentityScope(type);

        collectionGreeDaoDao = new CollectionGreeDaoDao(collectionGreeDaoDaoConfig, this);

        registerDao(CollectionGreeDao.class, collectionGreeDaoDao);
    }
    
    public void clear() {
        collectionGreeDaoDaoConfig.getIdentityScope().clear();
    }

    public CollectionGreeDaoDao getCollectionGreeDaoDao() {
        return collectionGreeDaoDao;
    }

}
