package comuxi.example.administrator.panda_channel.MyCollectGreeDao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import comuxi.example.administrator.panda_channel.MyCollectGreeDao.HistroyGreeDao;

import comuxi.example.administrator.panda_channel.MyCollectGreeDao.HistroyGreeDaoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig histroyGreeDaoDaoConfig;

    private final HistroyGreeDaoDao histroyGreeDaoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        histroyGreeDaoDaoConfig = daoConfigMap.get(HistroyGreeDaoDao.class).clone();
        histroyGreeDaoDaoConfig.initIdentityScope(type);

        histroyGreeDaoDao = new HistroyGreeDaoDao(histroyGreeDaoDaoConfig, this);

        registerDao(HistroyGreeDao.class, histroyGreeDaoDao);
    }
    
    public void clear() {
        histroyGreeDaoDaoConfig.getIdentityScope().clear();
    }

    public HistroyGreeDaoDao getHistroyGreeDaoDao() {
        return histroyGreeDaoDao;
    }

}
